server:
  port: 8088
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgis?useSSL=false,public
    username: postgres
    password: 666888
    driver-class-name: org.postgresql.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

